# ligas.py
LIGAS = {
    1: {'nome': 'Premier League', 'pais': 'England'},
    12: {'nome': 'Championship', 'pais': 'England'},
    86: {'nome': 'League One', 'pais': 'England'},
    87: {'nome': 'League Two', 'pais': 'England'},
    91: {'nome': 'National League', 'pais': 'England'},
    7: {'nome': 'Champions League', 'pais': 'Europe'},
    8: {'nome': 'Europa League', 'pais': 'Europe'},
    83: {'nome': 'Conference League', 'pais': 'Europe'},
    27: {'nome': 'World Cup 2026', 'pais': 'International'},
    66: {'nome': 'UEFA Euro 2024', 'pais': 'Europe'},
    30: {'nome': 'Africa Cup of Nations 2023', 'pais': 'Africa'},
    29: {'nome': 'CAF Champions League', 'pais': 'Africa'},
    9: {'nome': 'Brasileirão Serie A', 'pais': 'Brazil'},
    34: {'nome': 'Brasileirão Serie B', 'pais': 'Brazil'},
    35: {'nome': 'Copa do Brasil', 'pais': 'Brazil'},
    5: {'nome': 'Bundesliga', 'pais': 'Germany'},
    43: {'nome': 'DFB Pokal', 'pais': 'Germany'},
    6: {'nome': 'Ligue 1', 'pais': 'France'},
    89: {'nome': 'Ligue 2', 'pais': 'France'},
    4: {'nome': 'Serie A', 'pais': 'Italy'},
    42: {'nome': 'Coppa Italia', 'pais': 'Italy'},
    10: {'nome': 'Eredivisie', 'pais': 'Netherlands'},
    49: {'nome': 'J1 League', 'pais': 'Japan'},
}